In [1]:
import pandas as pd

data = pd.read_excel('Life Expectancy Data.xlsx')
data.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [2]:
data.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                448
Population                         652
thinness  1-19 years                34
thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64

In [3]:
data.shape

(2938, 22)

In [2]:
data.fillna(data.median(numeric_only=True), inplace=True)

In [38]:
data.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
BMI                                0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
HIV/AIDS                           0
GDP                                0
Population                         0
thinness  1-19 years               0
thinness 5-9 years                 0
Income composition of resources    0
Schooling                          0
dtype: int64

In [3]:
data['Class Status'] = data['Status'].map({'Developing': 0, 'Developed': 1})

In [4]:
data.drop('Status', axis=1, inplace=True)

In [7]:
print((data['Class Status'] == 0).sum())
print((data['Class Status'] == 1).sum())

2426
512

In [8]:
data.shape

(2938, 22)

In [9]:
data.columns

Index(['Country', 'Year', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'under-five deaths', 'Polio', 'Total expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling',
       'Class Status'],
      dtype='object')

In [11]:
data.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Class Status
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,...,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,69.234717,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,...,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,0.174268
std,4.613841,9.509115,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,...,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,0.379405
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,...,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,0.000000
25%,2004.000000,63.200000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,...,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,0.000000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,...,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,0.000000
75%,2012.000000,75.600000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,...,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,0.000000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,...,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,1.000000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Life expectancy                  2938 non-null   float64
 3   Adult Mortality                  2938 non-null   float64
 4   infant deaths                    2938 non-null   int64
 5   Alcohol                          2938 non-null   float64
 6   percentage expenditure           2938 non-null   float64
 7   Hepatitis B                      2938 non-null   float64
 8   Measles                          2938 non-null   int64
 9   BMI                              2938 non-null   float64
 10  under-five deaths                2938 non-null   int64
 11  Polio                            2938 non-null   float64
 12  Total expenditure                2938 non-null   float64
 13  Diphtheria                       2938 non-null   float64
 14  HIV/AIDS                         2938 non-null   float64
 15  GDP                              2938 non-null   float64
 16  Population                       2938 non-null   float64
 17  thinness  1-19 years             2938 non-null   float64
 18  thinness 5-9 years               2938 non-null   float64
 19  Income composition of resources  2938 non-null   float64
 20  Schooling                        2938 non-null   float64
 21  Class Status                     2938 non-null   int64
dtypes: float64(16), int64(5), object(1)
memory usage: 505.1+ KB

In [5]:
x = data.drop(['Country', 'Year', 'Class Status'], axis=1)
y = data['Class Status']

In [9]:
from sklearn.model_selection import train_test_split, cross_validate, StratifiedKFold

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.3, stratify=y)

In [8]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression

pipeline_log = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', LogisticRegression())
])

pipeline_log.fit(x_train, y_train)
y_log = pipeline_log.predict(x_test)

log_report = classification_report(y_test, y_log)
print(log_report)

              precision    recall  f1-score   support

           0       0.98      0.92      0.95       728
           1       0.70      0.90      0.79       154

    accuracy                           0.91       882
   macro avg       0.84      0.91      0.87       882
weighted avg       0.93      0.91      0.92       882

In [31]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer

pipeline_knn = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', KNeighborsClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_knn,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.928,
 Desvio Padrão: 0.010

precision_0
 Média: 0.986,
 Desvio Padrão: 0.004

precision_1
 Média: 0.730,
 Desvio Padrão: 0.032

recall_0
 Média: 0.926,
 Desvio Padrão: 0.011

recall_1
 Média: 0.938,
 Desvio Padrão: 0.019

f1_0
 Média: 0.955,
 Desvio Padrão: 0.006

f1_1
 Média: 0.821,
 Desvio Padrão: 0.024

In [32]:
from sklearn.tree import DecisionTreeClassifier

pipeline_dt = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', DecisionTreeClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_dt,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.956,
 Desvio Padrão: 0.014

precision_0
 Média: 0.978,
 Desvio Padrão: 0.011

precision_1
 Média: 0.859,
 Desvio Padrão: 0.039

recall_0
 Média: 0.969,
 Desvio Padrão: 0.009

recall_1
 Média: 0.896,
 Desvio Padrão: 0.052

f1_0
 Média: 0.973,
 Desvio Padrão: 0.008

f1_1
 Média: 0.877,
 Desvio Padrão: 0.040

<div style="padding:25px; border-radius:12px; border:2px solid #ddd;">

<h1 style="text-align:center;">🌳 RandomForestClassifier</h1>

<p style="text-align:center; font-size:18px;">
    Segunda melhor performance!
</p>

</div>

In [35]:
from sklearn.ensemble import RandomForestClassifier

pipeline_rf = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', RandomForestClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_rf,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.979,
 Desvio Padrão: 0.010

precision_0
 Média: 0.995,
 Desvio Padrão: 0.004

precision_1
 Média: 0.911,
 Desvio Padrão: 0.046

recall_0
 Média: 0.979,
 Desvio Padrão: 0.011

recall_1
 Média: 0.978,
 Desvio Padrão: 0.017

f1_0
 Média: 0.987,
 Desvio Padrão: 0.006

f1_1
 Média: 0.943,
 Desvio Padrão: 0.026

In [36]:
from sklearn.svm import SVC

pipeline_svm = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', SVC())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_svm,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.916,
 Desvio Padrão: 0.010

precision_0
 Média: 0.990,
 Desvio Padrão: 0.005

precision_1
 Média: 0.687,
 Desvio Padrão: 0.029

recall_0
 Média: 0.908,
 Desvio Padrão: 0.014

recall_1
 Média: 0.955,
 Desvio Padrão: 0.022

f1_0
 Média: 0.947,
 Desvio Padrão: 0.007

f1_1
 Média: 0.799,
 Desvio Padrão: 0.018

In [37]:
from sklearn.naive_bayes import GaussianNB

pipeline_nb = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', GaussianNB())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_nb,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.788,
 Desvio Padrão: 0.023

precision_0
 Média: 0.988,
 Desvio Padrão: 0.008

precision_1
 Média: 0.451,
 Desvio Padrão: 0.027

recall_0
 Média: 0.753,
 Desvio Padrão: 0.030

recall_1
 Média: 0.955,
 Desvio Padrão: 0.031

f1_0
 Média: 0.854,
 Desvio Padrão: 0.018

f1_1
 Média: 0.612,
 Desvio Padrão: 0.025

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

pipeline_gb = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', GradientBoostingClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_gb,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.961,
 Desvio Padrão: 0.009

precision_0
 Média: 0.990,
 Desvio Padrão: 0.005

precision_1
 Média: 0.844,
 Desvio Padrão: 0.037

recall_0
 Média: 0.962,
 Desvio Padrão: 0.011

recall_1
 Média: 0.953,
 Desvio Padrão: 0.026

f1_0
 Média: 0.976,
 Desvio Padrão: 0.006

f1_1
 Média: 0.894,
 Desvio Padrão: 0.022

In [39]:
from sklearn.ensemble import AdaBoostClassifier

pipeline_adaboost = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', AdaBoostClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_adaboost,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.931,
 Desvio Padrão: 0.013

precision_0
 Média: 0.986,
 Desvio Padrão: 0.005

precision_1
 Média: 0.739,
 Desvio Padrão: 0.044

recall_0
 Média: 0.929,
 Desvio Padrão: 0.016

recall_1
 Média: 0.938,
 Desvio Padrão: 0.025

f1_0
 Média: 0.957,
 Desvio Padrão: 0.008

f1_1
 Média: 0.826,
 Desvio Padrão: 0.029

<div style="padding:25px; border-radius:12px; border:2px solid #ddd;">

<h1 style="text-align:center;">🌳 ExtraTreesClassifier</h1>

<p style="text-align:center; font-size:18px;">
    Melhor performance!
</p>
    
</div>

In [40]:
from sklearn.ensemble import ExtraTreesClassifier

pipeline_extrees = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', ExtraTreesClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_extrees,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.985,
 Desvio Padrão: 0.009

precision_0
 Média: 0.995,
 Desvio Padrão: 0.006

precision_1
 Média: 0.939,
 Desvio Padrão: 0.029

recall_0
 Média: 0.986,
 Desvio Padrão: 0.007

recall_1
 Média: 0.978,
 Desvio Padrão: 0.027

f1_0
 Média: 0.991,
 Desvio Padrão: 0.005

f1_1
 Média: 0.958,
 Desvio Padrão: 0.025

<div style="padding:25px; border-radius:12px; border:2px solid #ddd;">

<h1 style="text-align:center;">XGBoost</h1>

<p style="text-align:center; font-size:18px;">
    Segunda melhor performance!
</p>

</div>

In [16]:
%pip install xgboost

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\ugabr\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\ugabr\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ------- -------------------------------- 8.7/48.9 MB 43.7 MB/s eta 0:00:01
   ----------------- ---------------------- 22.0/48.9 MB 54.7 MB/s eta 0:00:01
   -------------------------------- ------- 39.3/48.9 MB 65.1 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 67.3 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 57.0 MB/s  0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1
Note: you may need to restart the kernel to use updated packages.

In [41]:
from xgboost import XGBClassifier

pipeline_xgb = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('model', XGBClassifier())
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': 'accuracy',
    
    'precision_0': make_scorer(precision_score, pos_label=0),
    'precision_1': make_scorer(precision_score, pos_label=1),
    
    'recall_0': make_scorer(recall_score, pos_label=0),
    'recall_1': make_scorer(recall_score, pos_label=1),
    
    'f1_0': make_scorer(f1_score, pos_label=0),
    'f1_1': make_scorer(f1_score, pos_label=1),
}

results = cross_validate(
    pipeline_xgb,
    x_train,
    y_train,
    cv=cv,
    scoring=scoring
)

for metrica in scoring:
    scores = results[f'test_{metrica}']

    print(f'{metrica}\n Média: {scores.mean():.3f},\n Desvio Padrão: {scores.std():.3f}')
    print()

accuracy
 Média: 0.980,
 Desvio Padrão: 0.006

precision_0
 Média: 0.992,
 Desvio Padrão: 0.003

precision_1
 Média: 0.925,
 Desvio Padrão: 0.019

recall_0
 Média: 0.984,
 Desvio Padrão: 0.004

recall_1
 Média: 0.961,
 Desvio Padrão: 0.016

f1_0
 Média: 0.988,
 Desvio Padrão: 0.003

f1_1
 Média: 0.943,
 Desvio Padrão: 0.016